resources:
  - ../../base

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: sample-app
      namespace: sample-app
    path: ingress-patch.json

